# GitHub Actions workflow for functions deployment
name: Functions Deploy
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Add build and deploy steps here